"""
Application-wide constants
"""
# Simulation constants
SIMULATION_MONTHS = 120  # 10 years
DEFAULT_TARGET_MULTIPLIER = 10.0  # Default target = application_rate * this multiplier
DEFAULT_TARGET_FALLBACK = 100.0

# Validation constants
VALID_CLIMATE_BUCKETS = ["COLD_WET", "TEMPERATE", "HOT_DRY"]
MIN_APPLICATION_RATE = 0.1
MAX_APPLICATION_RATE = 1000.0
MIN_SIZE_FRACTION = 0.001
MAX_SIZE_FRACTION = 100.0
MIN_CHEMISTRY_FACTOR = 0.0
MAX_CHEMISTRY_FACTOR = 1.0
MIN_TIME_MONTHS = 0.0
MAX_TIME_MONTHS = 1200.0  # 100 years
MIN_CO2_UPTAKE = 0.0
MAX_CO2_UPTAKE = 10.0
MIN_WINDOW_MONTH = 0
MAX_WINDOW_MONTH = 1200
MIN_CO2_REMOVED = 0.0
MAX_CO2_REMOVED = 10000.0
MIN_N_RUNS = 1
MAX_N_RUNS = 100000

# Rate limiting constants
RATE_LIMIT_PER_MINUTE = 60
RATE_LIMIT_PER_HOUR = 1000

